const Products = {
  products: [
    {
      id: 12,
      sku: 12064273040195392,
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSizes: ["S", "XS"],
      style: "Black with custom print",
      price: 10.9,
      installments: 9,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 13,
      sku: 51498472915966370,
      title: "Dark Thug Blue-Navy T-Shirt",
      description: "Men's T-Shirt",
      availableSizes: ["M"],
      style: "Front print and paisley print",
      price: 29.45,
      installments: 5,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 14,
      sku: 10686354557628304,
      title: "Sphynx Tie Dye Wine T-Shirt",
      description: "GPX Poly 1",
      availableSizes: ["X", "L", "XL"],
      style: "Front tie dye print",
      price: 9,
      installments: 3,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 15,
      sku: 11033926921508488,
      title: "Skuul",
      description: "Treino 2014",
      availableSizes: ["X", "L", "XL", "XXL"],
      style: "Black T-Shirt with front print",
      price: 14,
      installments: 5,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 11,
      sku: 39876704341265610,
      title: "Wine Skul T-Shirt",
      description: "Men's Sprots T-Shirt",
      availableSizes: ["X", "L"],
      style: "Wine",
      price: 13.25,
      installments: 3,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 16,
      sku: 10412368723880252,
      title: "Short Sleeve T-Shirt",
      description: "Summer T-Shirt",
      availableSizes: ["XS", "X", "L", "ML", "XL"],
      style: "Grey",
      price: 75,
      installments: 5,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 0,
      sku: 8552515751438644,
      title: "Cat Tee Black T-Shirt",
      description: "Casual T-Shirt for Men",
      availableSizes: ["X", "L", "XL", "XXL"],
      style: "Branco com listras pretas",
      price: 10.9,
      installments: 9,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 1,
      sku: 18644119330491310,
      title: "Sphynx Tie Dye Grey T-Shirt",
      description: "Casual T-Shirt for Men",
      availableSizes: ["X", "L", "XL", "XXL"],
      style: "Preta com listras brancas",
      price: 10.9,
      installments: 9,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 2,
      sku: 11854078013954528,
      title: "Danger Knife Grey",
      description: "Casual T-Shirt for Men",
      availableSizes: ["X", "L"],
      style: "Branco com listras pretas",
      price: 14.9,
      installments: 7,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 3,
      sku: 876661122392077,
      title: "White DGK Script Tee",
      description: "Summer Vacation T-Shirt",
      availableSizes: ["X", "L"],
      style: "Preto com listras brancas",
      price: 14.9,
      installments: 7,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 4,
      sku: 9197907543445676,
      title: "Born On The Streets",
      description: "Winter Jogador T-Shirt",
      availableSizes: ["XL"],
      style: "Branco com listras pretas",
      price: 25.9,
      installments: 12,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: false,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 5,
      sku: 10547961582846888,
      title: "Tso 3D Short Sleeve T-Shirt A",
      description: "14/15 + Camiseta 1º Mundial",
      availableSizes: ["X", "L", "XL"],
      style: "Preto",
      price: 10.9,
      installments: 9,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: false,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 6,
      sku: 6090484789343891,
      title: "Man Tie Dye Cinza Grey T-Shirt",
      description: "Goleiro 13/14",
      availableSizes: ["XL", "XXL"],
      style: "Branco",
      price: 49.9,
      installments: 0,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 7,
      sku: 18532669286405344,
      title: "Crazy Monkey Black T-Shirt",
      description: "1977 Infantil",
      availableSizes: ["S"],
      style: "Preto com listras brancas",
      price: 22.5,
      installments: 4,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 8,
      sku: 5619496040738316,
      title: "Tso 3D Black T-Shirt",
      description: "Hot Spring Adult T-Shirt",
      availableSizes: ["XL"],
      style: "Azul escuro",
      price: 18.7,
      installments: 4,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: false,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 9,
      sku: 11600983276356164,
      title: "Crazy Monkey Grey",
      description: "Spring Adult T-Shirt",
      availableSizes: ["L", "XL"],
      style: "",
      price: 134.9,
      installments: 5,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    },
    {
      id: 10,
      sku: 27250082398145996,
      title: "On The Streets Black T-Shirt",
      description: "Spring Adult T-Shirt",
      availableSizes: ["L", "XL"],
      style: "",
      price: 49,
      installments: 9,
      currencyId: "USD",
      currencyFormat: "$",
      isFreeShipping: true,
      minOrderQuantity: 1,
      orderQuantity: 1
    }
  ]
};

export default Products;
